### ISSUE TITLE
Using an array for pre/post_cmd in hiera doesn't work as it gets interpreted as a Tuple

### ISSUE THREAD

**Issue by swantzter** [syseleven/puppet-restic#27]
With this example hiera data

```yaml
---
lookup_options:
  restic::repositories:
    merge: deep

restic::repositories:
  default:
    backup_pre_cmd:
      - /usr/bin/echo "Hello"
      - /usr/bin/echo "World"
```

You get the error

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Restic]:
  parameter 'repositories' entry 'default' entry 'backup_pre_cmd' expects a value of type Undef or String, got Tuple
```

Which to me seems weird given an array should be allowed per

https://github.com/syseleven/puppet-restic/blob/4c9360b3957d74b4d7b681ed0fcf1b43550017fd/manifests/repository.pp#L104

I'm not sure what the proper way around this would be, would it be a possibility to allow a tuple to deal with hiera, or is there a way to force hiera to coerce it to an array (I've not found anything about that)
